name: tuupai
description: Tuupai Prototype

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  flutter_swiper: ^1.1.6
  badges: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: NotoSansKr
      fonts:
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Regular.otf
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Thin.otf
          weight: 100
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Black.otf
          weight: 900
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/quicksand/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/quicksand/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/quicksand/Quicksand-Bold.ttf
          weight: 700
